repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.12.4
  hooks:
    - id: ruff
      args: [ --fix ]
    - id: ruff-format
- repo: https://github.com/PyCQA/isort
  rev: 6.0.1
  hooks:
  - id: isort

